[package]
name = "blockic"
version = "0.1.0"
authors = ["Friz64 <friz64mc@gmail.com>"]
edition = "2018"

[dependencies]
rendy = { git = "https://github.com/omni-viral/rendy.git" }
ansi_term = "0.11"
chrono = "0.4"
log = { version = "0.4", features = ["std"] }
clap = "2.33"
